/*
    Copyright 2013 Google Inc

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*/
(function() {

    var namespace = WEBLAB.namespace("WEBLAB.robots.constants");

    if (namespace.RobotsAnimatedIcons === undefined) {

        var RobotsAnimatedIcons = function RobotsAnimatedIcons() {
            //MENOTE: do nothing
        };

        namespace.RobotsAnimatedIcons = RobotsAnimatedIcons;


        RobotsAnimatedIcons.LOADING_ICON = {
            "tags": [{
                "bounds": [{
                    "ymin": -346,
                    "ymax": 347,
                    "xmin": -367,
                    "xmax": 367
                }],
                "id": 1,
                "paths": [{
                    "fill": 0,
                    "data": ["mhllz:67C47c34g67C93F67C93f"]
                }],
                "fillstyles": [{
                    "color": [-16764160],
                    "type": 1
                }],
                "type": 1
            }, {
                "bounds": [{
                    "ymin": 0,
                    "ymax": 693,
                    "xmin": 0,
                    "xmax": 734
                }],
                "id": 2,
                "paths": [{
                    "fill": 0,
                    "data": ["mlhlz:67c:67C93f34g67C93F"]
                }],
                "fillstyles": [{
                    "transform": ["5464F464f464f5608F59c3H"],
                    "type": 2,
                    "gradient": {
                        "stops": [{
                            "color": [-11447],
                            "offset": [0]
                        }, {
                            "color": [-2657107],
                            "offset": [255]
                        }]
                    }
                }],
                "type": 1
            }, {
                "tags": [{
                    "id": 2,
                    "matrix": 0,
                    "type": 3,
                    "depth": 1
                }, {
                    "type": 2
                }],
                "id": 3,
                "frameCount": 1,
                "type": 7
            }, {
                "bounds": [{
                    "ymin": 331,
                    "ymax": 460,
                    "xmin": 774,
                    "xmax": 782
                }, {
                    "ymin": 331,
                    "ymax": 460,
                    "xmin": -16,
                    "xmax": 782
                }],
                "id": 4,
                "paths": [{
                    "fill": 0,
                    "data": ["mhvhvz:74g31ch9lH9L", "mhvhvz:P31c98g9l98G9L"]
                }, {
                    "data": ["mhvhv:74g31ch9lH9L", "mhvhv:P31c98g9l98G9L"],
                    "line": 0
                }],
                "fillstyles": [{
                    "color": [-16764160],
                    "type": 1
                }],
                "linestyles": [{
                    "color": [0],
                    "width": [0]
                }],
                "type": 1
            }, {
                "bounds": [{
                    "ymin": 0,
                    "ymax": 960,
                    "xmin": 0,
                    "xmax": 798
                }],
                "id": 5,
                "paths": [{
                    "fill": 0,
                    "data": ["mhvhvzmhvhvz:70f31h42E04G42e04g70F9l98g60I98G60i"]
                }],
                "fillstyles": [{
                    "transform": ["0768F100e100e0304G46j71k"],
                    "type": 2,
                    "gradient": {
                        "stops": [{
                            "color": [-11447],
                            "offset": [0]
                        }, {
                            "color": [-1203078],
                            "offset": [130]
                        }, {
                            "color": [-2657107],
                            "offset": [255]
                        }]
                    }
                }],
                "type": 1
            }, {
                "tags": [{
                    "id": 5,
                    "matrix": 0,
                    "type": 3,
                    "depth": 1
                }, {
                    "type": 2
                }],
                "id": 6,
                "frameCount": 1,
                "type": 7
            }, {
                "bounds": [{
                    "ymin": -243,
                    "ymax": 243,
                    "xmin": -217,
                    "xmax": 217
                }],
                "id": 7,
                "paths": [{
                    "fill": 0,
                    "data": ["mlllz:0q3x7d86D34D8v87c8y"]
                }],
                "fillstyles": [{
                    "color": [-16764160],
                    "type": 1
                }],
                "type": 1
            }, {
                "bounds": [{
                    "ymin": 0,
                    "ymax": 486,
                    "xmin": 0,
                    "xmax": 434
                }],
                "id": 8,
                "paths": [{
                    "fill": 0,
                    "data": ["mlllz:87c86d7d86D34D8v87c8y"]
                }],
                "fillstyles": [{
                    "transform": ["6842F03t03t4230F89b1u"],
                    "type": 2,
                    "gradient": {
                        "stops": [{
                            "color": [-11447],
                            "offset": [0]
                        }, {
                            "color": [-2657107],
                            "offset": [255]
                        }]
                    }
                }],
                "type": 1
            }, {
                "tags": [{
                    "id": 8,
                    "matrix": 0,
                    "type": 3,
                    "depth": 1
                }, {
                    "type": 2
                }],
                "id": 9,
                "frameCount": 1,
                "type": 7
            }, {
                "bounds": [{
                    "ymin": 0,
                    "ymax": 292,
                    "xmin": 0,
                    "xmax": 228
                }],
                "id": 10,
                "paths": [{
                    "fill": 0,
                    "data": ["mlllz:3g:3G9m8v3o5O92B"]
                }],
                "fillstyles": [{
                    "transform": ["5398F12C12C5674F7o7k"],
                    "type": 2,
                    "gradient": {
                        "stops": [{
                            "color": [-2327702],
                            "offset": [0]
                        }, {
                            "color": [-2063775],
                            "offset": [255]
                        }]
                    }
                }],
                "type": 1
            }, {
                "tags": [{
                    "id": 10,
                    "matrix": 0,
                    "type": 3,
                    "depth": 1
                }, {
                    "type": 2
                }],
                "id": 11,
                "frameCount": 1,
                "type": 7
            }, {
                "bounds": [{
                    "ymin": 331,
                    "ymax": 460,
                    "xmin": -16,
                    "xmax": 782
                }],
                "id": 12,
                "paths": [{
                    "fill": 0,
                    "data": ["mhvhvz:82g31c98G9l98g9L"]
                }],
                "fillstyles": [{
                    "color": [-16764160],
                    "type": 1
                }],
                "type": 1
            }, {
                "bounds": [{
                    "ymin": 264,
                    "ymax": 460,
                    "xmin": -16,
                    "xmax": 782
                }, {
                    "ymin": -506,
                    "ymax": 460,
                    "xmin": -16,
                    "xmax": 782
                }],
                "id": 13,
                "paths": [{
                    "fill": 0,
                    "data": ["mhvhvhvhvz:P4z8l7f42eA8l0m98G6S", "mhvhvhvhvz:P06E8l37h42eA8l0m98G66I"]
                }, {
                    "data": ["mhvhvhvhv:P4z8l7f42eA8l0m98G6S", "mhvhvhvhv:P06E8l37h42eA8l0m98G66I"],
                    "line": 0
                }],
                "fillstyles": [{
                    "color": [-16764160],
                    "type": 1
                }],
                "linestyles": [{
                    "color": [0],
                    "width": [0]
                }],
                "type": 1
            }, {
                "bounds": [{
                    "ymin": -127,
                    "ymax": 128,
                    "xmin": -275,
                    "xmax": 276
                }],
                "id": 14,
                "paths": [{
                    "fill": 0,
                    "data": ["mlllz:76b8l15E5Y6C6r51e9f"]
                }],
                "fillstyles": [{
                    "color": [-16764160],
                    "type": 1
                }],
                "type": 1
            }, {
                "bounds": [{
                    "ymin": 0,
                    "ymax": 255,
                    "xmin": 0,
                    "xmax": 551
                }],
                "id": 15,
                "paths": [{
                    "fill": 0,
                    "data": ["mlllz:6c:6C6r51e9f15E5Y"]
                }],
                "fillstyles": [{
                    "transform": ["2824G42T42t2824G20h96e"],
                    "type": 2,
                    "gradient": {
                        "stops": [{
                            "color": [-11447],
                            "offset": [0]
                        }, {
                            "color": [-2657107],
                            "offset": [255]
                        }]
                    }
                }],
                "type": 1
            }, {
                "tags": [{
                    "id": 15,
                    "matrix": 0,
                    "type": 3,
                    "depth": 1
                }, {
                    "type": 2
                }],
                "id": 16,
                "frameCount": 1,
                "type": 7
            }, {
                "bounds": [{
                    "ymin": -506,
                    "ymax": 460,
                    "xmin": -16,
                    "xmax": 782
                }],
                "id": 17,
                "paths": [{
                    "fill": 0,
                    "data": ["mvhvhvhvhz:2k31c37H8L66i98g0M8La42E"]
                }],
                "fillstyles": [{
                    "color": [-16764160],
                    "type": 1
                }],
                "type": 1
            }, {
                "bounds": [{
                    "ymin": -506,
                    "ymax": 460,
                    "xmin": -16,
                    "xmax": 782
                }],
                "id": 18,
                "paths": [{
                    "fill": 0,
                    "data": ["mhvhvhvhvhvz:P06E9m3mK04g42eA8l0m98G66I", "mhvhvhvhvhvz:P06E98g3m70F04g42eA8l0m98G66I"]
                }, {
                    "data": ["mhvhvhvhvhv:P06E9m3mK04g42eA8l0m98G66I", "mhvhvhvhvhv:P06E98g3m70F04g42eA8l0m98G66I"],
                    "line": 0
                }],
                "fillstyles": [{
                    "color": [-16764160],
                    "type": 1
                }],
                "linestyles": [{
                    "color": [0],
                    "width": [0]
                }],
                "type": 1
            }, {
                "bounds": [{
                    "ymin": -156,
                    "ymax": -126,
                    "xmin": -15,
                    "xmax": 56
                }],
                "id": 19,
                "paths": [{
                    "fill": 0,
                    "data": ["mllvz:O5M1gi1G0Cu"]
                }],
                "fillstyles": [{
                    "color": [-2657931],
                    "type": 1
                }],
                "type": 1
            }, {
                "bounds": [{
                    "ymin": -188,
                    "ymax": -120,
                    "xmin": -15,
                    "xmax": 112
                }],
                "id": 20,
                "paths": [{
                    "fill": 0,
                    "data": ["mlvlvz:2k4M7L4E3e7loN"]
                }],
                "fillstyles": [{
                    "color": [-2657931],
                    "type": 1
                }],
                "type": 1
            }, {
                "bounds": [{
                    "ymin": -215,
                    "ymax": -91,
                    "xmin": -16,
                    "xmax": 113
                }],
                "id": 21,
                "paths": [{
                    "fill": 0,
                    "data": ["mllllz:3k0N9L5Ga9i7lya9D"]
                }],
                "fillstyles": [{
                    "color": [-2657931],
                    "type": 1
                }],
                "type": 1
            }, {
                "bounds": [{
                    "ymin": -160,
                    "ymax": 160,
                    "xmin": -79,
                    "xmax": 80
                }],
                "id": 22,
                "paths": [{
                    "fill": 0,
                    "data": ["mqvqqqz:4c3K7D7D3K7D20c6f:3k7D6d7D6d3K:6F6D3K"]
                }],
                "fillstyles": [{
                    "color": [-13159115],
                    "type": 1
                }],
                "type": 1
            }, {
                "bounds": [{
                    "ymin": -357,
                    "ymax": -102,
                    "xmin": -303,
                    "xmax": 248
                }, {
                    "ymin": -352,
                    "ymax": -165,
                    "xmin": -292,
                    "xmax": 312
                }],
                "id": 23,
                "paths": [{
                    "fill": 0,
                    "data": ["mlllz:03C1Q6c6R15e5y51E9F", "mlllz:92B7P7d5R57e7r04FB"]
                }, {
                    "data": ["mlll:03C1Q6c6R15e5y51E9F", "mlll:92B7P7d5R57e7r04FB"],
                    "line": 0
                }],
                "fillstyles": [{
                    "transform": ["2824G42T42t2824G17e9w"],
                    "type": 2,
                    "gradient": {
                        "stops": [{
                            "color": [-11447],
                            "offset": [0]
                        }, {
                            "color": [-2657107],
                            "offset": [255]
                        }]
                    }
                }],
                "linestyles": [{
                    "color": [0],
                    "width": [0]
                }],
                "type": 1
            }, {
                "bounds": [{
                    "ymin": -185,
                    "ymax": 38,
                    "xmin": 245,
                    "xmax": 543
                }],
                "id": 24,
                "paths": [{
                    "fill": 0,
                    "data": ["mlqqqqvlvz:28e7cm1Dj5F9B7K9C2E2J2F4FI6K9b3Cw9D9ea83b2mA"]
                }],
                "fillstyles": [{
                    "transform": ["5140G85D85D5932E10iB"],
                    "type": 2,
                    "gradient": {
                        "stops": [{
                            "color": [-11447],
                            "offset": [0]
                        }, {
                            "color": [-2657107],
                            "offset": [255]
                        }]
                    }
                }],
                "type": 1
            }, {
                "bounds": [{
                    "ymin": -506,
                    "ymax": 460,
                    "xmin": -16,
                    "xmax": 782
                }],
                "id": 25,
                "paths": [{
                    "fill": 0,
                    "data": ["mhvhvhvhvhvz:2k73C70f3M98G66i98g0M8La42E04G"]
                }],
                "fillstyles": [{
                    "color": [-16764160],
                    "type": 1
                }],
                "type": 1
            }, {
                "bounds": [{
                    "ymin": -506,
                    "ymax": 460,
                    "xmin": -16,
                    "xmax": 782
                }],
                "id": 26,
                "paths": [{
                    "fill": 0,
                    "data": ["mhvhvhvhvhvhvz:P06E98g7n0MN40E04g42eA8l0m98G66I", "mhvhvhvhvhvhvz:P06E98g25h0M92F40E04g42eA8l0m98G66I"]
                }, {
                    "data": ["mhvhvhvhvhvhv:P06E98g7n0MN40E04g42eA8l0m98G66I", "mhvhvhvhvhvhv:P06E98g25h0M92F40E04g42eA8l0m98G66I"],
                    "line": 0
                }],
                "fillstyles": [{
                    "color": [-16764160],
                    "type": 1
                }],
                "linestyles": [{
                    "color": [0],
                    "width": [0]
                }],
                "type": 1
            }, {
                "bounds": [{
                    "ymin": -352,
                    "ymax": -165,
                    "xmin": -292,
                    "xmax": 312
                }, {
                    "ymin": -346,
                    "ymax": -163,
                    "xmin": -279,
                    "xmax": 433
                }],
                "id": 27,
                "paths": [{
                    "fill": 0,
                    "data": ["mlllz:92B7P7d5R57e7r04FB", "mlllz:79B3P0f3R52f9p12Gn"]
                }, {
                    "data": ["mlll:92B7P7d5R57e7r04FB", "mlll:79B3P0f3R52f9p12Gn"],
                    "line": 0
                }],
                "fillstyles": [{
                    "transform": ["2824G42T42t2824G17e9w"],
                    "type": 2,
                    "gradient": {
                        "stops": [{
                            "color": [-11447],
                            "offset": [0]
                        }, {
                            "color": [-2657107],
                            "offset": [255]
                        }]
                    }
                }],
                "linestyles": [{
                    "color": [0],
                    "width": [0]
                }],
                "type": 1
            }, {
                "bounds": [{
                    "ymin": -263,
                    "ymax": -166,
                    "xmin": -16,
                    "xmax": 112
                }],
                "id": 28,
                "paths": [{
                    "fill": 0,
                    "data": ["mlvhlz:1k8U7L5D7i8lA2E"]
                }],
                "fillstyles": [{
                    "color": [-2657931],
                    "type": 1
                }],
                "type": 1
            }, {
                "bounds": [{
                    "ymin": -277,
                    "ymax": -167,
                    "xmin": -16,
                    "xmax": 112
                }],
                "id": 29,
                "paths": [{
                    "fill": 0,
                    "data": ["mlvhvz:2k6W8L1D0k8l9F"]
                }],
                "fillstyles": [{
                    "color": [-2657931],
                    "type": 1
                }],
                "type": 1
            }, {
                "bounds": [{
                    "ymin": -282,
                    "ymax": -139,
                    "xmin": -16,
                    "xmax": 112
                }],
                "id": 30,
                "paths": [{
                    "fill": 0,
                    "data": ["mlvlvz:2k1X8L1D6m8lg2J"]
                }],
                "fillstyles": [{
                    "color": [-2657931],
                    "type": 1
                }],
                "type": 1
            }, {
                "bounds": [{
                    "ymin": -346,
                    "ymax": -163,
                    "xmin": -279,
                    "xmax": 433
                }, {
                    "ymin": -339,
                    "ymax": -86,
                    "xmin": -263,
                    "xmax": 533
                }],
                "id": 31,
                "paths": [{
                    "fill": 0,
                    "data": ["mlllz:79B3P0f3R52f9p12Gn", "mlllz:3Z8O5g1R21g3y96G2G"]
                }, {
                    "data": ["mlll:79B3P0f3R52f9p12Gn", "mlll:3Z8O5g1R21g3y96G2G"],
                    "line": 0
                }],
                "fillstyles": [{
                    "transform": ["2824G42T42t2824G17e9w"],
                    "type": 2,
                    "gradient": {
                        "stops": [{
                            "color": [-11447],
                            "offset": [0]
                        }, {
                            "color": [-2657107],
                            "offset": [255]
                        }]
                    }
                }],
                "linestyles": [{
                    "color": [0],
                    "width": [0]
                }],
                "type": 1
            }, {
                "bounds": [{
                    "ymin": -506,
                    "ymax": 460,
                    "xmin": -16,
                    "xmax": 782
                }],
                "id": 32,
                "paths": [{
                    "fill": 0,
                    "data": ["mvhvhvhvhvhvhz:2k31c04G40e92f0m25H98G66i98g0M8La42E"]
                }],
                "fillstyles": [{
                    "color": [-16764160],
                    "type": 1
                }],
                "type": 1
            }, {
                "bounds": [{
                    "ymin": -500,
                    "ymax": 460,
                    "xmin": -16,
                    "xmax": 782
                }],
                "id": 33,
                "paths": [{
                    "fill": 0,
                    "data": ["mvhvhzmhvhvz:54f73C04g42E04G42e8l7L98G60i98g60I"]
                }],
                "fillstyles": [{
                    "color": [-16764160],
                    "type": 1
                }],
                "type": 1
            }, {
                "bounds": [{
                    "ymin": -269,
                    "ymax": -104,
                    "xmin": -17,
                    "xmax": 112
                }],
                "id": 34,
                "paths": [{
                    "fill": 0,
                    "data": ["mlllvz:2k7U7L2EB7n9lr3K"]
                }],
                "fillstyles": [{
                    "color": [-2657931],
                    "type": 1
                }],
                "type": 1
            }, {
                "bounds": [{
                    "ymin": -339,
                    "ymax": -86,
                    "xmin": -263,
                    "xmax": 533
                }, {
                    "ymin": -333,
                    "ymax": 37,
                    "xmin": -250,
                    "xmax": 525
                }],
                "id": 35,
                "paths": [{
                    "fill": 0,
                    "data": ["mlllz:3Z8O5g1R21g3y96G2G", "mlllz:0Y3O8h0R87f70c75G0S"]
                }, {
                    "data": ["mlll:3Z8O5g1R21g3y96G2G", "mlll:0Y3O8h0R87f70c75G0S"],
                    "line": 0
                }],
                "fillstyles": [{
                    "transform": ["2824G42T42t2824G17e9w"],
                    "type": 2,
                    "gradient": {
                        "stops": [{
                            "color": [-11447],
                            "offset": [0]
                        }, {
                            "color": [-2657107],
                            "offset": [255]
                        }]
                    }
                }],
                "linestyles": [{
                    "color": [0],
                    "width": [0]
                }],
                "type": 1
            }, {
                "bounds": [{
                    "ymin": -253,
                    "ymax": -65,
                    "xmin": -16,
                    "xmax": 112
                }],
                "id": 36,
                "paths": [{
                    "fill": 0,
                    "data": ["mlllvz:2k5R7L8FA7o8l1c0L"]
                }],
                "fillstyles": [{
                    "color": [-2657931],
                    "type": 1
                }],
                "type": 1
            }, {
                "bounds": [{
                    "ymin": -103,
                    "ymax": 118,
                    "xmin": 234,
                    "xmax": 532
                }],
                "id": 37,
                "paths": [{
                    "fill": 0,
                    "data": ["mllqqqqz:32e9b83B2MM1dJ4f8b7k8c2e2j1f4fk7k8B3cX9d9E"]
                }],
                "fillstyles": [{
                    "transform": ["5140G85D85D5932E14iK"],
                    "type": 2,
                    "gradient": {
                        "stops": [{
                            "color": [-11447],
                            "offset": [0]
                        }, {
                            "color": [-2657107],
                            "offset": [255]
                        }]
                    }
                }],
                "type": 1
            }, {
                "bounds": [{
                    "ymin": -333,
                    "ymax": 37,
                    "xmin": -250,
                    "xmax": 525
                }, {
                    "ymin": -339,
                    "ymax": 118,
                    "xmin": -263,
                    "xmax": 440
                }],
                "id": 38,
                "paths": [{
                    "fill": 0,
                    "data": ["mlllz:0Y3O8h0R87f70c75G0S", "mlllz:3Z7O5g2R28f57d03G75B"]
                }, {
                    "data": ["mlll:0Y3O8h0R87f70c75G0S", "mlll:3Z7O5g2R28f57d03G75B"],
                    "line": 0
                }],
                "fillstyles": [{
                    "transform": ["2824G42T42t2824G17e9w"],
                    "type": 2,
                    "gradient": {
                        "stops": [{
                            "color": [-11447],
                            "offset": [0]
                        }, {
                            "color": [-2657107],
                            "offset": [255]
                        }]
                    }
                }],
                "linestyles": [{
                    "color": [0],
                    "width": [0]
                }],
                "type": 1
            }, {
                "bounds": [{
                    "ymin": -57,
                    "ymax": 53,
                    "xmin": 388,
                    "xmax": 532
                }],
                "id": 39,
                "paths": [{
                    "fill": 0,
                    "data": ["mlllllqz:16d7EYlCq4g2f5esoZcS6K4H"]
                }],
                "fillstyles": [{
                    "transform": ["5140G85D85D5932E05im"],
                    "type": 2,
                    "gradient": {
                        "stops": [{
                            "color": [-11447],
                            "offset": [0]
                        }, {
                            "color": [-2657107],
                            "offset": [255]
                        }]
                    }
                }],
                "type": 1
            }, {
                "bounds": [{
                    "ymin": -229,
                    "ymax": -30,
                    "xmin": -16,
                    "xmax": 113
                }],
                "id": 40,
                "paths": [{
                    "fill": 0,
                    "data": ["mlvllz:2k4N8L5H5o9l4dA4K"]
                }],
                "fillstyles": [{
                    "color": [-2657931],
                    "type": 1
                }],
                "type": 1
            }, {
                "bounds": [{
                    "ymin": -339,
                    "ymax": 118,
                    "xmin": -263,
                    "xmax": 440
                }, {
                    "ymin": -345,
                    "ymax": 101,
                    "xmin": -276,
                    "xmax": 319
                }],
                "id": 41,
                "paths": [{
                    "fill": 0,
                    "data": ["mlllz:3Z7O5g2R28f57d03G75B", "mlllz:76B2P2f3R33e46d95E3Z"]
                }, {
                    "data": ["mlll:3Z7O5g2R28f57d03G75B", "mlll:76B2P2f3R33e46d95E3Z"],
                    "line": 0
                }],
                "fillstyles": [{
                    "transform": ["2824G42T42t2824G17e9w"],
                    "type": 2,
                    "gradient": {
                        "stops": [{
                            "color": [-11447],
                            "offset": [0]
                        }, {
                            "color": [-2657107],
                            "offset": [255]
                        }]
                    }
                }],
                "linestyles": [{
                    "color": [0],
                    "width": [0]
                }],
                "type": 1
            }, {
                "bounds": [{
                    "ymin": -205,
                    "ymax": -7,
                    "xmin": -16,
                    "xmax": 113
                }],
                "id": 42,
                "paths": [{
                    "fill": 0,
                    "data": ["mllllz:3k9J8L6IA7n8l1ea2J"]
                }],
                "fillstyles": [{
                    "color": [-2657931],
                    "type": 1
                }],
                "type": 1
            }, {
                "bounds": [{
                    "ymin": -188,
                    "ymax": 3,
                    "xmin": -16,
                    "xmax": 112
                }],
                "id": 43,
                "paths": [{
                    "fill": 0,
                    "data": ["mlvllz:P1E8l4e9H7L2JA7m"]
                }],
                "fillstyles": [{
                    "color": [-2657931],
                    "type": 1
                }],
                "type": 1
            }, {
                "bounds": [{
                    "ymin": -345,
                    "ymax": 101,
                    "xmin": -276,
                    "xmax": 319
                }, {
                    "ymin": -351,
                    "ymax": 22,
                    "xmin": -289,
                    "xmax": 239
                }],
                "id": 44,
                "paths": [{
                    "fill": 0,
                    "data": ["mlllz:76B2P2f3R33e46d95E3Z", "mlllz:89B6P9d5R79d73c28E8R"]
                }, {
                    "data": ["mlll:76B2P2f3R33e46d95E3Z", "mlll:89B6P9d5R79d73c28E8R"],
                    "line": 0
                }],
                "fillstyles": [{
                    "transform": ["2824G42T42t2824G17e9w"],
                    "type": 2,
                    "gradient": {
                        "stops": [{
                            "color": [-11447],
                            "offset": [0]
                        }, {
                            "color": [-2657107],
                            "offset": [255]
                        }]
                    }
                }],
                "linestyles": [{
                    "color": [0],
                    "width": [0]
                }],
                "type": 1
            }, {
                "bounds": [{
                    "ymin": -178,
                    "ymax": 1,
                    "xmin": -16,
                    "xmax": 112
                }],
                "id": 45,
                "paths": [{
                    "fill": 0,
                    "data": ["mlllvz:P2E7l3ea4G8L5J6l"]
                }],
                "fillstyles": [{
                    "color": [-2657931],
                    "type": 1
                }],
                "type": 1
            }, {
                "bounds": [{
                    "ymin": -351,
                    "ymax": 22,
                    "xmin": -289,
                    "xmax": 239
                }, {
                    "ymin": -357,
                    "ymax": -102,
                    "xmin": -303,
                    "xmax": 248
                }],
                "id": 46,
                "paths": [{
                    "fill": 0,
                    "data": ["mlllz:89B6P9d5R79d73c28E8R", "mlllz:03C1Q6c6R15e5y51E9F"]
                }, {
                    "data": ["mlll:89B6P9d5R79d73c28E8R", "mlll:03C1Q6c6R15e5y51E9F"],
                    "line": 0
                }],
                "fillstyles": [{
                    "transform": ["2824G42T42t2824G17e9w"],
                    "type": 2,
                    "gradient": {
                        "stops": [{
                            "color": [-11447],
                            "offset": [0]
                        }, {
                            "color": [-2657107],
                            "offset": [255]
                        }]
                    }
                }],
                "linestyles": [{
                    "color": [0],
                    "width": [0]
                }],
                "type": 1
            }, {
                "bounds": [{
                    "ymin": -112,
                    "ymax": 53,
                    "xmin": 239,
                    "xmax": 532
                }],
                "id": 47,
                "paths": [{
                    "fill": 0,
                    "data": ["mlllhlqz:72b2KYlHy77b8laoZcS0Z9M"]
                }],
                "fillstyles": [{
                    "transform": ["5140G85D85D5932E05im"],
                    "type": 2,
                    "gradient": {
                        "stops": [{
                            "color": [-11447],
                            "offset": [0]
                        }, {
                            "color": [-2657107],
                            "offset": [255]
                        }]
                    }
                }],
                "type": 1
            }, {
                "bounds": [{
                    "ymin": -357,
                    "ymax": -102,
                    "xmin": -303,
                    "xmax": 248
                }],
                "id": 48,
                "paths": [{
                    "fill": 0,
                    "data": ["mlllz:7Z57C6C6r51e9f15E5Y"]
                }],
                "fillstyles": [{
                    "transform": ["2824G42T42t2824G17e9w"],
                    "type": 2,
                    "gradient": {
                        "stops": [{
                            "color": [-11447],
                            "offset": [0]
                        }, {
                            "color": [-2657107],
                            "offset": [255]
                        }]
                    }
                }],
                "type": 1
            }, {
                "tags": [{
                    "clip": 11,
                    "id": 1,
                    "matrix": "::::33E13h",
                    "type": 3,
                    "depth": 8
                }, {
                    "id": 3,
                    "matrix": "::::00I3W",
                    "type": 3,
                    "depth": 9
                }, {
                    "type": 2
                }, {
                    "replace": true,
                    "matrix": "::::33E28g",
                    "type": 3,
                    "depth": 8
                }, {
                    "type": 2
                }, {
                    "replace": true,
                    "matrix": "::::33E49f",
                    "type": 3,
                    "depth": 8
                }, {
                    "type": 2
                }, {
                    "replace": true,
                    "matrix": "::::33E75e",
                    "type": 3,
                    "depth": 8
                }, {
                    "type": 2
                }, {
                    "replace": true,
                    "matrix": "::::33E07e",
                    "type": 3,
                    "depth": 8
                }, {
                    "type": 2
                }, {
                    "replace": true,
                    "matrix": "::::33E44d",
                    "type": 3,
                    "depth": 8
                }, {
                    "type": 2
                }, {
                    "replace": true,
                    "matrix": "::::33E86c",
                    "type": 3,
                    "depth": 8
                }, {
                    "type": 2
                }, {
                    "replace": true,
                    "matrix": "::::33E34c",
                    "type": 3,
                    "depth": 8
                }, {
                    "type": 2
                }, {
                    "replace": true,
                    "matrix": "::::33E88b",
                    "type": 3,
                    "depth": 8
                }, {
                    "type": 2
                }, {
                    "replace": true,
                    "matrix": "::::33E7x",
                    "type": 3,
                    "depth": 8
                }, {
                    "type": 2
                }, {
                    "replace": true,
                    "matrix": "::::33E1u",
                    "type": 3,
                    "depth": 8
                }, {
                    "clip": 19,
                    "id": 4,
                    "matrix": 0,
                    "type": 3,
                    "depth": 16
                }, {
                    "id": 6,
                    "ratio": 10,
                    "matrix": "::::P00E",
                    "type": 3,
                    "depth": 17
                }, {
                    "type": 2
                }, {
                    "replace": true,
                    "matrix": "::::33E1r",
                    "type": 3,
                    "depth": 8
                }, {
                    "replace": true,
                    "ratio": 10923,
                    "type": 3,
                    "depth": 16
                }, {
                    "type": 2
                }, {
                    "replace": true,
                    "matrix": "::::33E7o",
                    "type": 3,
                    "depth": 8
                }, {
                    "replace": true,
                    "ratio": 21845,
                    "type": 3,
                    "depth": 16
                }, {
                    "type": 2
                }, {
                    "replace": true,
                    "matrix": "::::33E8m",
                    "type": 3,
                    "depth": 8
                }, {
                    "clip": 15,
                    "id": 7,
                    "matrix": "::::16G76E",
                    "type": 3,
                    "depth": 12
                }, {
                    "id": 9,
                    "ratio": 13,
                    "matrix": "::::65G27D",
                    "type": 3,
                    "depth": 13
                }, {
                    "replace": true,
                    "ratio": 32768,
                    "type": 3,
                    "depth": 16
                }, {
                    "clip": 27,
                    "id": 7,
                    "matrix": "::::16G76E",
                    "type": 3,
                    "depth": 24
                }, {
                    "id": 11,
                    "ratio": 13,
                    "matrix": "::::05F4W",
                    "type": 3,
                    "depth": 25
                }, {
                    "type": 2
                }, {
                    "replace": true,
                    "matrix": "::::33E4l",
                    "type": 3,
                    "depth": 8
                }, {
                    "replace": true,
                    "matrix": "::::89F13E",
                    "type": 3,
                    "depth": 12
                }, {
                    "replace": true,
                    "ratio": 43691,
                    "type": 3,
                    "depth": 16
                }, {
                    "replace": true,
                    "matrix": "::::89F13E",
                    "type": 3,
                    "depth": 24
                }, {
                    "type": 2
                }, {
                    "replace": true,
                    "matrix": "::::33E6k",
                    "type": 3,
                    "depth": 8
                }, {
                    "replace": true,
                    "matrix": "::::65F56D",
                    "type": 3,
                    "depth": 12
                }, {
                    "replace": true,
                    "ratio": 54613,
                    "type": 3,
                    "depth": 16
                }, {
                    "replace": true,
                    "matrix": "::::65F56D",
                    "type": 3,
                    "depth": 24
                }, {
                    "type": 2
                }, {
                    "type": 4,
                    "depth": 16
                }, {
                    "type": 4,
                    "depth": 17
                }, {
                    "replace": true,
                    "matrix": "::::33E3k",
                    "type": 3,
                    "depth": 8
                }, {
                    "replace": true,
                    "matrix": "::::43F04D",
                    "type": 3,
                    "depth": 12
                }, {
                    "clip": 19,
                    "id": 12,
                    "matrix": 0,
                    "type": 3,
                    "depth": 16
                }, {
                    "id": 6,
                    "ratio": 16,
                    "matrix": "::::P00E",
                    "type": 3,
                    "depth": 17
                }, {
                    "replace": true,
                    "matrix": "::::43F04D",
                    "type": 3,
                    "depth": 24
                }, {
                    "type": 2
                }, {
                    "type": 4,
                    "depth": 16
                }, {
                    "type": 4,
                    "depth": 17
                }, {
                    "replace": true,
                    "matrix": "::::23F58C",
                    "type": 3,
                    "depth": 12
                }, {
                    "clip": 19,
                    "id": 13,
                    "matrix": 0,
                    "type": 3,
                    "depth": 16
                }, {
                    "id": 6,
                    "ratio": 17,
                    "matrix": "::::P00E",
                    "type": 3,
                    "depth": 17
                }, {
                    "replace": true,
                    "matrix": "::::23F58C",
                    "type": 3,
                    "depth": 24
                }, {
                    "type": 2
                }, {
                    "replace": true,
                    "matrix": "::::05F17C",
                    "type": 3,
                    "depth": 12
                }, {
                    "replace": true,
                    "ratio": 10923,
                    "type": 3,
                    "depth": 16
                }, {
                    "replace": true,
                    "matrix": "::::05F17C",
                    "type": 3,
                    "depth": 24
                }, {
                    "type": 2
                }, {
                    "replace": true,
                    "matrix": "::::90E82B",
                    "type": 3,
                    "depth": 12
                }, {
                    "replace": true,
                    "ratio": 21845,
                    "type": 3,
                    "depth": 16
                }, {
                    "replace": true,
                    "matrix": "::::90E82B",
                    "type": 3,
                    "depth": 24
                }, {
                    "type": 2
                }, {
                    "replace": true,
                    "matrix": "::::77E2Y",
                    "type": 3,
                    "depth": 12
                }, {
                    "replace": true,
                    "ratio": 32768,
                    "type": 3,
                    "depth": 16
                }, {
                    "replace": true,
                    "matrix": "::::77E2Y",
                    "type": 3,
                    "depth": 24
                }, {
                    "type": 2
                }, {
                    "replace": true,
                    "matrix": "::::67E8V",
                    "type": 3,
                    "depth": 12
                }, {
                    "replace": true,
                    "ratio": 43691,
                    "type": 3,
                    "depth": 16
                }, {
                    "replace": true,
                    "matrix": "::::67E8V",
                    "type": 3,
                    "depth": 24
                }, {
                    "type": 2
                }, {
                    "replace": true,
                    "matrix": "::::58E8T",
                    "type": 3,
                    "depth": 12
                }, {
                    "replace": true,
                    "ratio": 54613,
                    "type": 3,
                    "depth": 16
                }, {
                    "clip": 23,
                    "id": 14,
                    "matrix": "::::81E00C",
                    "type": 3,
                    "depth": 20
                }, {
                    "id": 16,
                    "ratio": 22,
                    "matrix": "::::03C57C",
                    "type": 3,
                    "depth": 21
                }, {
                    "replace": true,
                    "matrix": "::::58E8T",
                    "type": 3,
                    "depth": 24
                }, {
                    "type": 2
                }, {
                    "type": 4,
                    "depth": 16
                }, {
                    "type": 4,
                    "depth": 17
                }, {
                    "replace": true,
                    "matrix": "::::53E5S",
                    "type": 3,
                    "depth": 12
                }, {
                    "clip": 19,
                    "id": 17,
                    "matrix": 0,
                    "type": 3,
                    "depth": 16
                }, {
                    "id": 6,
                    "ratio": 23,
                    "matrix": "::::P00E",
                    "type": 3,
                    "depth": 17
                }, {
                    "replace": true,
                    "matrix": "182f27f::06D77B",
                    "type": 3,
                    "depth": 20
                }, {
                    "replace": true,
                    "matrix": "::::53E5S",
                    "type": 3,
                    "depth": 24
                }, {
                    "type": 2
                }, {
                    "type": 4,
                    "depth": 16
                }, {
                    "type": 4,
                    "depth": 17
                }, {
                    "replace": true,
                    "matrix": "::::49E7R",
                    "type": 3,
                    "depth": 12
                }, {
                    "clip": 19,
                    "id": 18,
                    "matrix": 0,
                    "type": 3,
                    "depth": 16
                }, {
                    "id": 6,
                    "ratio": 24,
                    "matrix": "::::P00E",
                    "type": 3,
                    "depth": 17
                }, {
                    "replace": true,
                    "matrix": "987j50j::8Z9Y",
                    "type": 3,
                    "depth": 20
                }, {
                    "replace": true,
                    "matrix": "::::49E7R",
                    "type": 3,
                    "depth": 24
                }, {
                    "id": 19,
                    "matrix": 0,
                    "type": 3,
                    "depth": 28
                }, {
                    "type": 2
                }, {
                    "replace": true,
                    "matrix": "::::48E4R",
                    "type": 3,
                    "depth": 12
                }, {
                    "replace": true,
                    "ratio": 13107,
                    "type": 3,
                    "depth": 16
                }, {
                    "replace": true,
                    "matrix": "418n57n::2Q6X",
                    "type": 3,
                    "depth": 20
                }, {
                    "replace": true,
                    "matrix": "::::48E4R",
                    "type": 3,
                    "depth": 24
                }, {
                    "replace": true,
                    "id": 20,
                    "type": 3,
                    "depth": 28
                }, {
                    "type": 2
                }, {
                    "type": 4,
                    "depth": 12
                }, {
                    "type": 4,
                    "depth": 13
                }, {
                    "id": 9,
                    "ratio": 26,
                    "matrix": "::::65G27D",
                    "type": 3,
                    "depth": 12
                }, {
                    "replace": true,
                    "ratio": 26214,
                    "type": 3,
                    "depth": 16
                }, {
                    "replace": true,
                    "matrix": "473p23r::3K9W",
                    "type": 3,
                    "depth": 20
                }, {
                    "replace": true,
                    "id": 21,
                    "matrix": "16J::084Ta7E",
                    "type": 3,
                    "depth": 28
                }, {
                    "type": 2
                }, {
                    "type": 4,
                    "depth": 21
                }, {
                    "type": 4,
                    "depth": 24
                }, {
                    "type": 4,
                    "depth": 25
                }, {
                    "type": 4,
                    "depth": 28
                }, {
                    "clip": 3,
                    "id": 22,
                    "matrix": "3299I9364e9364E3299I53c3d",
                    "type": 3,
                    "depth": 1
                }, {
                    "replace": true,
                    "ratio": 39322,
                    "type": 3,
                    "depth": 16
                }, {
                    "replace": true,
                    "matrix": "160q18t::4I6W",
                    "type": 3,
                    "depth": 20
                }, {
                    "id": 23,
                    "matrix": 0,
                    "type": 3,
                    "depth": 21
                }, {
                    "clip": 28,
                    "id": 9,
                    "ratio": 27,
                    "matrix": "::::65G27D",
                    "type": 3,
                    "depth": 24
                }, {
                    "id": 11,
                    "ratio": 27,
                    "matrix": "::::05F4W",
                    "type": 3,
                    "depth": 26
                }, {
                    "id": 21,
                    "matrix": "08E::384P:2E",
                    "type": 3,
                    "depth": 30
                }, {
                    "type": 2
                }, {
                    "replace": true,
                    "matrix": "3627J3203e3203E3627J41c5c",
                    "type": 3,
                    "depth": 1
                }, {
                    "id": 24,
                    "matrix": 0,
                    "type": 3,
                    "depth": 2
                }, {
                    "replace": true,
                    "matrix": "I96h96HI58G32D",
                    "type": 3,
                    "depth": 12
                }, {
                    "replace": true,
                    "ratio": 52429,
                    "type": 3,
                    "depth": 16
                }, {
                    "replace": true,
                    "matrix": "400rB:24j2F0X",
                    "type": 3,
                    "depth": 20
                }, {
                    "replace": true,
                    "ratio": 21845,
                    "type": 3,
                    "depth": 21
                }, {
                    "replace": true,
                    "matrix": "I96h96HI58G32D",
                    "type": 3,
                    "depth": 24
                }, {
                    "replace": true,
                    "matrix": "08E::326O:6F",
                    "type": 3,
                    "depth": 30
                }, {
                    "type": 2
                }, {
                    "type": 4,
                    "depth": 16
                }, {
                    "type": 4,
                    "depth": 17
                }, {
                    "replace": true,
                    "matrix": "2725K5320d5320D2725K30cz",
                    "type": 3,
                    "depth": 1
                }, {
                    "replace": true,
                    "matrix": "8C06t06T8C50G38D",
                    "type": 3,
                    "depth": 12
                }, {
                    "clip": 17,
                    "id": 25,
                    "matrix": 0,
                    "type": 3,
                    "depth": 14
                }, {
                    "id": 6,
                    "ratio": 29,
                    "matrix": "::::P00E",
                    "type": 3,
                    "depth": 15
                }, {
                    "replace": true,
                    "matrix": "588s17S:48t0C3X",
                    "type": 3,
                    "depth": 20
                }, {
                    "replace": true,
                    "ratio": 43691,
                    "type": 3,
                    "depth": 21
                }, {
                    "replace": true,
                    "matrix": "8C06t06T8C50G38D",
                    "type": 3,
                    "depth": 24
                }, {
                    "replace": true,
                    "matrix": "08E::798N:2H",
                    "type": 3,
                    "depth": 30
                }, {
                    "type": 2
                }, {
                    "type": 4,
                    "depth": 14
                }, {
                    "type": 4,
                    "depth": 15
                }, {
                    "replace": true,
                    "matrix": "0354L5734c5734C0354L19cm",
                    "type": 3,
                    "depth": 1
                }, {
                    "replace": true,
                    "matrix": "4G901b901B4G42G44D",
                    "type": 3,
                    "depth": 12
                }, {
                    "clip": 17,
                    "id": 26,
                    "matrix": 0,
                    "type": 3,
                    "depth": 14
                }, {
                    "id": 6,
                    "ratio": 30,
                    "matrix": "::::P00E",
                    "type": 3,
                    "depth": 15
                }, {
                    "replace": true,
                    "matrix": "717t166D:072cc7X",
                    "type": 3,
                    "depth": 20
                }, {
                    "replace": true,
                    "id": 27,
                    "ratio": 0,
                    "type": 3,
                    "depth": 21
                }, {
                    "replace": true,
                    "matrix": "4G901b901B4G42G44D",
                    "type": 3,
                    "depth": 24
                }, {
                    "replace": true,
                    "id": 28,
                    "matrix": 0,
                    "type": 3,
                    "depth": 30
                }, {
                    "type": 2
                }, {
                    "replace": true,
                    "matrix": "5990L102y102Y5990L13ca",
                    "type": 3,
                    "depth": 1
                }, {
                    "replace": true,
                    "matrix": "6M009d009D6M34G50D",
                    "type": 3,
                    "depth": 12
                }, {
                    "replace": true,
                    "ratio": 10923,
                    "type": 3,
                    "depth": 14
                }, {
                    "replace": true,
                    "matrix": "806u193F:096d6c1Y",
                    "type": 3,
                    "depth": 20
                }, {
                    "replace": true,
                    "ratio": 13107,
                    "type": 3,
                    "depth": 21
                }, {
                    "replace": true,
                    "matrix": "6M009d009D6M34G50D",
                    "type": 3,
                    "depth": 24
                }, {
                    "replace": true,
                    "id": 29,
                    "type": 3,
                    "depth": 30
                }, {
                    "type": 2
                }, {
                    "replace": true,
                    "matrix": "9639L415m415M9639L09cO",
                    "type": 3,
                    "depth": 1
                }, {
                    "replace": true,
                    "matrix": "0T903d903D0T28G55D",
                    "type": 3,
                    "depth": 12
                }, {
                    "replace": true,
                    "ratio": 21845,
                    "type": 3,
                    "depth": 14
                }, {
                    "replace": true,
                    "matrix": "836v698H:120e8f5Y",
                    "type": 3,
                    "depth": 20
                }, {
                    "replace": true,
                    "ratio": 26214,
                    "type": 3,
                    "depth": 21
                }, {
                    "replace": true,
                    "matrix": "0T903d903D0T28G55D",
                    "type": 3,
                    "depth": 24
                }, {
                    "replace": true,
                    "id": 30,
                    "matrix": ":::374L:4E",
                    "type": 3,
                    "depth": 30
                }, {
                    "type": 2
                }, {
                    "type": 4,
                    "depth": 20
                }, {
                    "type": 4,
                    "depth": 21
                }, {
                    "replace": true,
                    "matrix": "1048M75n75N1048M06c0C",
                    "type": 3,
                    "depth": 1
                }, {
                    "replace": true,
                    "matrix": "96B009f009F96B20G60D",
                    "type": 3,
                    "depth": 12
                }, {
                    "replace": true,
                    "ratio": 32768,
                    "type": 3,
                    "depth": 14
                }, {
                    "id": 27,
                    "ratio": 39322,
                    "matrix": 0,
                    "type": 3,
                    "depth": 18
                }, {
                    "replace": true,
                    "matrix": "96B009f009F96B20G60D",
                    "type": 3,
                    "depth": 24
                }, {
                    "replace": true,
                    "matrix": ":::541J:0E",
                    "type": 3,
                    "depth": 30
                }, {
                    "type": 2
                }, {
                    "replace": true,
                    "matrix": "0222M304J304j0222M07c4D",
                    "type": 3,
                    "depth": 1
                }, {
                    "replace": true,
                    "matrix": "87C900f900F87C11G65D",
                    "type": 3,
                    "depth": 12
                }, {
                    "replace": true,
                    "ratio": 43691,
                    "type": 3,
                    "depth": 14
                }, {
                    "replace": true,
                    "ratio": 52429,
                    "type": 3,
                    "depth": 18
                }, {
                    "replace": true,
                    "matrix": "87C900f900F87C11G65D",
                    "type": 3,
                    "depth": 24
                }, {
                    "replace": true,
                    "matrix": ":::082J:1E",
                    "type": 3,
                    "depth": 30
                }, {
                    "type": 2
                }, {
                    "replace": true,
                    "matrix": "7141L151V151v7141L11c9E",
                    "type": 3,
                    "depth": 1
                }, {
                    "replace": true,
                    "matrix": "17E003h003H17E03G71D",
                    "type": 3,
                    "depth": 12
                }, {
                    "replace": true,
                    "ratio": 54613,
                    "type": 3,
                    "depth": 14
                }, {
                    "replace": true,
                    "id": 31,
                    "ratio": 0,
                    "type": 3,
                    "depth": 18
                }, {
                    "replace": true,
                    "matrix": "17E003h003H17E03G71D",
                    "type": 3,
                    "depth": 24
                }, {
                    "replace": true,
                    "matrix": ":::708H:8D",
                    "type": 3,
                    "depth": 30
                }, {
                    "type": 2
                }, {
                    "type": 4,
                    "depth": 14
                }, {
                    "type": 4,
                    "depth": 15
                }, {
                    "replace": true,
                    "matrix": "2023L3041C3041c2023L19c2G",
                    "type": 3,
                    "depth": 1
                }, {
                    "replace": true,
                    "matrix": "35F891h891H35F96F75D",
                    "type": 3,
                    "depth": 12
                }, {
                    "clip": 17,
                    "id": 32,
                    "matrix": 0,
                    "type": 3,
                    "depth": 14
                }, {
                    "id": 6,
                    "ratio": 36,
                    "matrix": "::::P00E",
                    "type": 3,
                    "depth": 15
                }, {
                    "replace": true,
                    "ratio": 10923,
                    "type": 3,
                    "depth": 18
                }, {
                    "replace": true,
                    "matrix": "35F891h891H35F96F75D",
                    "type": 3,
                    "depth": 24
                }, {
                    "replace": true,
                    "matrix": ":::874F:8C",
                    "type": 3,
                    "depth": 30
                }, {
                    "type": 2
                }, {
                    "type": 4,
                    "depth": 14
                }, {
                    "type": 4,
                    "depth": 15
                }, {
                    "replace": true,
                    "matrix": "5005K2821D2821d5005K28c4H",
                    "type": 3,
                    "depth": 1
                }, {
                    "replace": true,
                    "matrix": "99G990i990I99G87F81D",
                    "type": 3,
                    "depth": 12
                }, {
                    "clip": 17,
                    "id": 33,
                    "matrix": 0,
                    "type": 3,
                    "depth": 14
                }, {
                    "id": 6,
                    "ratio": 37,
                    "matrix": "::::P00E",
                    "type": 3,
                    "depth": 15
                }, {
                    "replace": true,
                    "ratio": 21845,
                    "type": 3,
                    "depth": 18
                }, {
                    "replace": true,
                    "matrix": "99G990i990I99G87F81D",
                    "type": 3,
                    "depth": 24
                }, {
                    "replace": true,
                    "matrix": "12E::583DaY",
                    "type": 3,
                    "depth": 30
                }, {
                    "type": 2
                }, {
                    "replace": true,
                    "matrix": "6155J1294E1294e6155J39c5I",
                    "type": 3,
                    "depth": 1
                }, {
                    "replace": true,
                    "matrix": "44I874j874J44I78F84D",
                    "type": 3,
                    "depth": 12
                }, {
                    "replace": true,
                    "ratio": 32768,
                    "type": 3,
                    "depth": 18
                }, {
                    "replace": true,
                    "matrix": "44I874j874J44I78F84D",
                    "type": 3,
                    "depth": 24
                }, {
                    "replace": true,
                    "matrix": "12e::91VAL",
                    "type": 3,
                    "depth": 30
                }, {
                    "type": 2
                }, {
                    "replace": true,
                    "matrix": "6081I7881E7881e6081I52c4J",
                    "type": 3,
                    "depth": 1
                }, {
                    "replace": true,
                    "matrix": "42K967k967K42K70F90D",
                    "type": 3,
                    "depth": 12
                }, {
                    "replace": true,
                    "ratio": 43691,
                    "type": 3,
                    "depth": 18
                }, {
                    "replace": true,
                    "matrix": "42K967k967K42K70F90D",
                    "type": 3,
                    "depth": 24
                }, {
                    "replace": true,
                    "matrix": 0,
                    "type": 3,
                    "depth": 30
                }, {
                    "type": 2
                }, {
                    "replace": true,
                    "matrix": "4980H2520F2520f4980H64c8J",
                    "type": 3,
                    "depth": 1
                }, {
                    "replace": true,
                    "matrix": "14M847l847L14M63F93D",
                    "type": 3,
                    "depth": 12
                }, {
                    "replace": true,
                    "ratio": 54613,
                    "type": 3,
                    "depth": 18
                }, {
                    "replace": true,
                    "matrix": "14M847l847L14M63F93D",
                    "type": 3,
                    "depth": 24
                }, {
                    "replace": true,
                    "id": 34,
                    "matrix": ":::752Fa8C",
                    "type": 3,
                    "depth": 30
                }, {
                    "type": 2
                }, {
                    "replace": true,
                    "matrix": "3011G5081F5081f3011G80c3K",
                    "type": 3,
                    "depth": 1
                }, {
                    "replace": true,
                    "matrix": "44O934m934M44O53F99D",
                    "type": 3,
                    "depth": 12
                }, {
                    "replace": true,
                    "id": 35,
                    "ratio": 0,
                    "type": 3,
                    "depth": 18
                }, {
                    "replace": true,
                    "matrix": "44O934m934M44O53F99D",
                    "type": 3,
                    "depth": 24
                }, {
                    "replace": true,
                    "matrix": "08E::766Da9B",
                    "type": 3,
                    "depth": 30
                }, {
                    "type": 2
                }, {
                    "replace": true,
                    "matrix": "1209F5378F5378f1209F94c3K",
                    "type": 3,
                    "depth": 1
                }, {
                    "replace": true,
                    "matrix": "44Q807n807N44Q46F02E",
                    "type": 3,
                    "depth": 12
                }, {
                    "replace": true,
                    "ratio": 21845,
                    "type": 3,
                    "depth": 18
                }, {
                    "replace": true,
                    "matrix": "44Q807n807N44Q46F02E",
                    "type": 3,
                    "depth": 24
                }, {
                    "replace": true,
                    "matrix": 0,
                    "type": 3,
                    "depth": 30
                }, {
                    "type": 2
                }, {
                    "replace": true,
                    "matrix": "9341D3448F3448f9341D08d9J",
                    "type": 3,
                    "depth": 1
                }, {
                    "replace": true,
                    "matrix": "07T887o887O07T36F06E",
                    "type": 3,
                    "depth": 12
                }, {
                    "replace": true,
                    "ratio": 43691,
                    "type": 3,
                    "depth": 18
                }, {
                    "replace": true,
                    "matrix": "07T887o887O07T36F06E",
                    "type": 3,
                    "depth": 24
                }, {
                    "replace": true,
                    "id": 36,
                    "matrix": ":::532D:X",
                    "type": 3,
                    "depth": 30
                }, {
                    "type": 2
                }, {
                    "replace": true,
                    "matrix": "7772C9364E9364e7772C20d9I",
                    "type": 3,
                    "depth": 1
                }, {
                    "clip": 6,
                    "id": 22,
                    "matrix": "7772C9364E9364e7772C20d9I",
                    "type": 3,
                    "depth": 4
                }, {
                    "id": 37,
                    "matrix": 0,
                    "type": 3,
                    "depth": 5
                }, {
                    "replace": true,
                    "matrix": "33V960p960P33V27F11E",
                    "type": 3,
                    "depth": 12
                }, {
                    "replace": true,
                    "id": 38,
                    "ratio": 0,
                    "type": 3,
                    "depth": 18
                }, {
                    "replace": true,
                    "matrix": "33V960p960P33V27F11E",
                    "type": 3,
                    "depth": 24
                }, {
                    "replace": true,
                    "matrix": 0,
                    "type": 3,
                    "depth": 30
                }, {
                    "type": 2
                }, {
                    "replace": true,
                    "matrix": "175W9846D9846d175W36d7H",
                    "type": 3,
                    "depth": 4
                }, {
                    "id": 39,
                    "matrix": 0,
                    "type": 3,
                    "depth": 7
                }, {
                    "replace": true,
                    "matrix": "02T863o863O02T37F07E",
                    "type": 3,
                    "depth": 12
                }, {
                    "replace": true,
                    "ratio": 21845,
                    "type": 3,
                    "depth": 18
                }, {
                    "replace": true,
                    "matrix": "77R361o361O77R41F04E",
                    "type": 3,
                    "depth": 24
                }, {
                    "replace": true,
                    "id": 40,
                    "matrix": ":::47PAS",
                    "type": 3,
                    "depth": 30
                }, {
                    "type": 2
                }, {
                    "replace": true,
                    "matrix": "874K7397C7397c874K49d5G",
                    "type": 3,
                    "depth": 4
                }, {
                    "replace": true,
                    "matrix": "36Q769n769N36Q45F02E",
                    "type": 3,
                    "depth": 12
                }, {
                    "replace": true,
                    "ratio": 43691,
                    "type": 3,
                    "depth": 18
                }, {
                    "replace": true,
                    "matrix": "01P185n185N01P52F99D",
                    "type": 3,
                    "depth": 24
                }, {
                    "replace": true,
                    "matrix": 0,
                    "type": 3,
                    "depth": 30
                }, {
                    "type": 2
                }, {
                    "replace": true,
                    "matrix": "471D483W483w471D58d8E",
                    "type": 3,
                    "depth": 4
                }, {
                    "replace": true,
                    "matrix": "90N679m679M90N56F98D",
                    "type": 3,
                    "depth": 12
                }, {
                    "replace": true,
                    "id": 41,
                    "ratio": 0,
                    "type": 3,
                    "depth": 18
                }, {
                    "replace": true,
                    "matrix": "08M810l810L08M63F94D",
                    "type": 3,
                    "depth": 24
                }, {
                    "replace": true,
                    "id": 42,
                    "matrix": ":::86s:C",
                    "type": 3,
                    "depth": 30
                }, {
                    "type": 2
                }, {
                    "replace": true,
                    "matrix": "78F835H835h78F63d3D",
                    "type": 3,
                    "depth": 4
                }, {
                    "replace": true,
                    "matrix": "07M803l803L07M63F94D",
                    "type": 3,
                    "depth": 12
                }, {
                    "replace": true,
                    "ratio": 16384,
                    "type": 3,
                    "depth": 18
                }, {
                    "replace": true,
                    "matrix": "45J446k446K45J75F88D",
                    "type": 3,
                    "depth": 24
                }, {
                    "replace": true,
                    "matrix": 0,
                    "type": 3,
                    "depth": 30
                }, {
                    "type": 2
                }, {
                    "replace": true,
                    "matrix": "05C441e441E05C65d7B",
                    "type": 3,
                    "depth": 4
                }, {
                    "replace": true,
                    "matrix": "96J720k720K96J73F89D",
                    "type": 3,
                    "depth": 12
                }, {
                    "replace": true,
                    "ratio": 32768,
                    "type": 3,
                    "depth": 18
                }, {
                    "replace": true,
                    "matrix": "50H305j305J50H85F82D",
                    "type": 3,
                    "depth": 24
                }, {
                    "replace": true,
                    "id": 43,
                    "matrix": ":::16q:E",
                    "type": 3,
                    "depth": 30
                }, {
                    "type": 2
                }, {
                    "replace": true,
                    "matrix": "845B655r655R845B62dL",
                    "type": 3,
                    "depth": 4
                }, {
                    "replace": true,
                    "matrix": "43I856j856J43I80F84D",
                    "type": 3,
                    "depth": 12
                }, {
                    "replace": true,
                    "ratio": 49152,
                    "type": 3,
                    "depth": 18
                }, {
                    "replace": true,
                    "matrix": "77F176i176I77F94F76D",
                    "type": 3,
                    "depth": 24
                }, {
                    "replace": true,
                    "matrix": 0,
                    "type": 3,
                    "depth": 30
                }, {
                    "type": 2
                }, {
                    "replace": true,
                    "matrix": "734G0529c0529C734G57db",
                    "type": 3,
                    "depth": 4
                }, {
                    "replace": true,
                    "matrix": "01H997i997I01H87F81D",
                    "type": 3,
                    "depth": 12
                }, {
                    "replace": true,
                    "id": 44,
                    "ratio": 0,
                    "type": 3,
                    "depth": 18
                }, {
                    "replace": true,
                    "matrix": "53E273h273H53E02G73D",
                    "type": 3,
                    "depth": 24
                }, {
                    "replace": true,
                    "id": 45,
                    "matrix": ":::661c:i",
                    "type": 3,
                    "depth": 30
                }, {
                    "type": 2
                }, {
                    "replace": true,
                    "matrix": "450N0743d0743D450N48dm",
                    "type": 3,
                    "depth": 4
                }, {
                    "replace": true,
                    "matrix": "72F144i144I72F95F76D",
                    "type": 3,
                    "depth": 12
                }, {
                    "replace": true,
                    "ratio": 16384,
                    "type": 3,
                    "depth": 18
                }, {
                    "replace": true,
                    "matrix": "18D171g171G18D10G67D",
                    "type": 3,
                    "depth": 24
                }, {
                    "replace": true,
                    "matrix": 0,
                    "type": 3,
                    "depth": 30
                }, {
                    "type": 2
                }, {
                    "replace": true,
                    "matrix": "145V8846d8846D145V40dw",
                    "type": 3,
                    "depth": 4
                }, {
                    "replace": true,
                    "matrix": "56E297h297H56E02G73D",
                    "type": 3,
                    "depth": 12
                }, {
                    "replace": true,
                    "ratio": 32768,
                    "type": 3,
                    "depth": 18
                }, {
                    "replace": true,
                    "matrix": "25C298f298F25C17G62D",
                    "type": 3,
                    "depth": 24
                }, {
                    "replace": true,
                    "matrix": ":::63Y:G",
                    "type": 3,
                    "depth": 30
                }, {
                    "type": 2
                }, {
                    "replace": true,
                    "matrix": "0575C5193e5193E0575C30d0c",
                    "type": 3,
                    "depth": 4
                }, {
                    "replace": true,
                    "matrix": "51D456g456G51D07G68D",
                    "type": 3,
                    "depth": 12
                }, {
                    "replace": true,
                    "ratio": 49152,
                    "type": 3,
                    "depth": 18
                }, {
                    "replace": true,
                    "matrix": "5X439e439E5X24G58D",
                    "type": 3,
                    "depth": 24
                }, {
                    "replace": true,
                    "matrix": ":::591F:O",
                    "type": 3,
                    "depth": 30
                }, {
                    "type": 2
                }, {
                    "replace": true,
                    "matrix": "9137C9776e9776E9137C20d7c",
                    "type": 3,
                    "depth": 4
                }, {
                    "replace": true,
                    "matrix": "60C624f624F60C15G64D",
                    "type": 3,
                    "depth": 12
                }, {
                    "replace": true,
                    "id": 46,
                    "ratio": 0,
                    "type": 3,
                    "depth": 18
                }, {
                    "replace": true,
                    "matrix": "8Q595d595D8Q30G55D",
                    "type": 3,
                    "depth": 24
                }, {
                    "replace": true,
                    "matrix": ":::886I:Y",
                    "type": 3,
                    "depth": 30
                }, {
                    "type": 2
                }, {
                    "replace": true,
                    "matrix": "7473D2817f2817F7473D12d8c",
                    "type": 3,
                    "depth": 4
                }, {
                    "replace": true,
                    "matrix": "96B011f011F96B20G60D",
                    "type": 3,
                    "depth": 12
                }, {
                    "replace": true,
                    "ratio": 7965,
                    "type": 3,
                    "depth": 18
                }, {
                    "replace": true,
                    "matrix": "2L767c767C2L38G49D",
                    "type": 3,
                    "depth": 24
                }, {
                    "replace": true,
                    "matrix": ":::350Kc3C",
                    "type": 3,
                    "depth": 30
                }, {
                    "type": 2
                }, {
                    "replace": true,
                    "matrix": "5524E4609f4609F5524E02d0d",
                    "type": 3,
                    "depth": 4
                }, {
                    "replace": true,
                    "matrix": "3V193e193E3V26G55D",
                    "type": 3,
                    "depth": 12
                }, {
                    "replace": true,
                    "ratio": 15475,
                    "type": 3,
                    "depth": 18
                }, {
                    "replace": true,
                    "matrix": "8H170c170C8H42G45D",
                    "type": 3,
                    "depth": 24
                }, {
                    "replace": true,
                    "matrix": ":::547M:7D",
                    "type": 3,
                    "depth": 30
                }, {
                    "type": 2
                }, {
                    "replace": true,
                    "matrix": "2681F5336f5336F2681F95c1d",
                    "type": 3,
                    "depth": 4
                }, {
                    "replace": true,
                    "matrix": "8Q595d595D8Q30G55D",
                    "type": 3,
                    "depth": 12
                }, {
                    "replace": true,
                    "ratio": 22528,
                    "type": 3,
                    "depth": 18
                }, {
                    "replace": true,
                    "matrix": "2F86y86Y2F46G42D",
                    "type": 3,
                    "depth": 24
                }, {
                    "replace": true,
                    "id": 21,
                    "matrix": "08E::928g:5d",
                    "type": 3,
                    "depth": 30
                }, {
                    "type": 2
                }, {
                    "replace": true,
                    "matrix": "9253F5284f5284F9253F87c1d",
                    "type": 3,
                    "depth": 4
                }, {
                    "replace": true,
                    "matrix": "7M005d005D7M36G51D",
                    "type": 3,
                    "depth": 12
                }, {
                    "replace": true,
                    "ratio": 29127,
                    "type": 3,
                    "depth": 18
                }, {
                    "replace": true,
                    "matrix": "8C20t20T8C50G39D",
                    "type": 3,
                    "depth": 24
                }, {
                    "replace": true,
                    "matrix": ":::285e:2c",
                    "type": 3,
                    "depth": 30
                }, {
                    "type": 2
                }, {
                    "replace": true,
                    "matrix": "4958G4686f4686F4958G81c1d",
                    "type": 3,
                    "depth": 4
                }, {
                    "replace": true,
                    "matrix": "0I209c209C0I41G46D",
                    "type": 3,
                    "depth": 12
                }, {
                    "replace": true,
                    "ratio": 35272,
                    "type": 3,
                    "depth": 18
                }, {
                    "replace": true,
                    "matrix": "W70n70NW55G35D",
                    "type": 3,
                    "depth": 24
                }, {
                    "replace": true,
                    "matrix": ":::171c:s",
                    "type": 3,
                    "depth": 30
                }, {
                    "type": 2
                }, {
                    "replace": true,
                    "matrix": "9984G3729f3729F9984G75c9c",
                    "type": 3,
                    "depth": 4
                }, {
                    "replace": true,
                    "matrix": "3F35z35Z3F46G42D",
                    "type": 3,
                    "depth": 12
                }, {
                    "replace": true,
                    "ratio": 40960,
                    "type": 3,
                    "depth": 18
                }, {
                    "replace": true,
                    "matrix": "O51k51KO57G34D",
                    "type": 3,
                    "depth": 24
                }, {
                    "replace": true,
                    "matrix": ":::57j:h",
                    "type": 3,
                    "depth": 30
                }, {
                    "type": 2
                }, {
                    "replace": true,
                    "matrix": "4123H2634f2634F4123H71c8c",
                    "type": 3,
                    "depth": 4
                }, {
                    "replace": true,
                    "matrix": "2D67t67T2D50G39D",
                    "type": 3,
                    "depth": 12
                }, {
                    "replace": true,
                    "ratio": 46194,
                    "type": 3,
                    "depth": 18
                }, {
                    "replace": true,
                    "matrix": "E31f31FE61G32D",
                    "type": 3,
                    "depth": 24
                }, {
                    "replace": true,
                    "matrix": 0,
                    "type": 3,
                    "depth": 30
                }, {
                    "type": 2
                }, {
                    "replace": true,
                    "matrix": "7394H1557f1557F7394H66c6c",
                    "type": 3,
                    "depth": 4
                }, {
                    "replace": true,
                    "matrix": "0C24q24Q0C53G38D",
                    "type": 3,
                    "depth": 12
                }, {
                    "replace": true,
                    "ratio": 50973,
                    "type": 3,
                    "depth": 18
                }, {
                    "replace": true,
                    "matrix": "C45c45CC63G29D",
                    "type": 3,
                    "depth": 24
                }, {
                    "replace": true,
                    "matrix": "08E::14U:J",
                    "type": 3,
                    "depth": 30
                }, {
                    "type": 2
                }, {
                    "replace": true,
                    "matrix": "9830H0626f0626F9830H64c7c",
                    "type": 3,
                    "depth": 4
                }, {
                    "replace": true,
                    "id": 47,
                    "type": 3,
                    "depth": 7
                }, {
                    "replace": true,
                    "matrix": "O74k74KO56G35D",
                    "type": 3,
                    "depth": 12
                }, {
                    "replace": true,
                    "ratio": 55296,
                    "type": 3,
                    "depth": 18
                }, {
                    "replace": true,
                    "matrix": "C87b87BC63G28D",
                    "type": 3,
                    "depth": 24
                }, {
                    "replace": true,
                    "matrix": ":::42ZAR",
                    "type": 3,
                    "depth": 30
                }, {
                    "type": 2
                }, {
                    "replace": true,
                    "matrix": "1660I9854e9854E1660I62c5c",
                    "type": 3,
                    "depth": 4
                }, {
                    "replace": true,
                    "matrix": "E31f31FE61G32D",
                    "type": 3,
                    "depth": 12
                }, {
                    "replace": true,
                    "ratio": 59165,
                    "type": 3,
                    "depth": 18
                }, {
                    "replace": true,
                    "matrix": "B2c2CB66G28D",
                    "type": 3,
                    "depth": 24
                }, {
                    "replace": true,
                    "matrix": ":::228DAZ",
                    "type": 3,
                    "depth": 30
                }, {
                    "type": 2
                }, {
                    "replace": true,
                    "matrix": "2706I9382e9382E2706I61c4c",
                    "type": 3,
                    "depth": 4
                }, {
                    "replace": true,
                    "matrix": "C13c13CC63G29D",
                    "type": 3,
                    "depth": 12
                }, {
                    "replace": true,
                    "ratio": 62579,
                    "type": 3,
                    "depth": 18
                }, {
                    "replace": true,
                    "matrix": "AiIA66G28D",
                    "type": 3,
                    "depth": 24
                }, {
                    "replace": true,
                    "matrix": "08E::757D:1C",
                    "type": 3,
                    "depth": 30
                }, {
                    "type": 2
                }, {
                    "type": 4,
                    "depth": 18
                }, {
                    "type": 9,
                    "actions": [{
                        "type": 7
                    }]
                }, {
                    "replace": true,
                    "matrix": "3230I9230e9230E3230I60c5c",
                    "type": 3,
                    "depth": 4
                }, {
                    "replace": true,
                    "matrix": "::::65G27D",
                    "type": 3,
                    "depth": 12
                }, {
                    "id": 48,
                    "matrix": 0,
                    "type": 3,
                    "depth": 18
                }, {
                    "replace": true,
                    "matrix": "::::65G27D",
                    "type": 3,
                    "depth": 24
                }, {
                    "replace": true,
                    "matrix": "16J::342Fa8C",
                    "type": 3,
                    "depth": 30
                }, {
                    "type": 2
                }],
                "id": 49,
                "frameCount": 68,
                "type": 7
            }, {
                "id": 49,
                "matrix": "694R::694R22k90g",
                "type": 3,
                "depth": 1
            }, {
                "type": 2
            }],
            "v": "4.4.0",
            "backgroundColor": -1,
            "frameSize": {
                "ymin": 0,
                "ymax": 1600,
                "xmin": 0,
                "xmax": 2400
            },
            "frameCount": 1,
            "frameRate": 60,
            "code": "",
            "version": 8
        };

    }
})();
